### PR TITLE
Frontend/staging

### PR DESCRIPTION
**Pull request by AllisonRCook**
## Description
 
Implementation of frontend into main

**Summary**: 

**Issue Link**: #101 

## Type of action

- [ ] Bug fix 
- [x] New feature
- [ ] Requires a documentation update
- [ ] Others: 

## Checklist

- [ ] My code style is consistent with the current project
- [ ] I have done a brief review of my code
- [ ] I have written readable comments
- [ ] I have updated the documentation related to the changes I made
- [ ] I have written reasonable tests and the updated version all passed
- [ ] There should be no potential errors after the changes get merged into main

## Screenshots
N/A

# Action Required

Testing and integration with backend

### CODE REVIEW

**Comment by tusharagg1** [comment]
@AllisonRCook Can you take a look at the above checks and try to resolve them, if possible? They are associated mainly with the frontend and should be passing all checks.

**Comment by tusharagg1** [comment]
@AllisonRCook
Can you try installing the following extensions in your IDE:
- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
- [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)

This may help you with the remaining failing checks.

**Comment by AllisonRCook** [comment]
> @AllisonRCook Can you try installing the following extensions in your IDE:
> 
> * [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
> * [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
> * [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)
> 
> This may help you with the remaining failing checks.

I've fixed most issues, could I have this PR approved and merged so I can branch this code for the backend merge

**Comment by tusharagg1** [comment]
@AllisonRCook does this issue need to be closed or deleted?

**Pull request merged**
